  
swagger: "2.0"
info: 
  title: "Swagger Sample App"
  description: "Please to click Terms of service"
  termsOfService: "alert(1)"
  contact: 
    name: "API Support"
    url: "alert(1)"
    email: ":javascript:alert(document.cookie)"
version: "1.0.1"
