swagger: "2.0"
info: 
  title: "Swagger Sample App>"
  description: "Please to click Terms of service>"
  termsOfService: "vv>"
  contact: 
    name: "API Support>"
    url: "https://google.com/\"'>"
    email: "javascript:alert(document.cookie)"
version: "1.0.1"
